name: deck-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # Specify Python version
  - numpy        # Conda manages system-level packages like numpy
  - pip           # Install pip inside the environment
  - pip:
      - -r file:requirements.txt  # Install Python packages via pip from requirements.txt