name: rdnet-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12  # Specify Python version
  - numpy        # Conda manages system-level packages like numpy
  - pip           # Install pip inside the environment
  - pip:
      - onnxruntime
      - torch
      - torchvision
      - scikit-learn
      - timm
